### ISSUE TITLE
Issue Installing NVidia Cuda Upgrade

### ISSUE THREAD

**Issue by bradley-foord** [MishaSavchenko/valkyrie_issue_sync#2]
1. The install failed on the first step with the 'insight' module. doing a custom install and unselecting this option got around the problem.
2. The install failed for the Nsight Visual Studio Edition Summary with the following information:

```
Installed:
     - Nsight for Visual Studio 2019
     - Nsight Monitor
Not Installed:
     - Nsight for Visual Studio 2022
        Reason: VS2022 was not found
     - Integrated Graphics Frame Debugger and Profiler
        Reason: see https://developer.nvidia.com/nsight-vstools
     - Integrated CUDA Profilers
       Reason: see https://developer.nvidia.com/nsight-vstools
```
